### ISSUE TITLE
Installing collected packages: fastapi

### ISSUE THREAD

**Issue by dodoaska** [Deepanjalkumar/Attacksurfacemanagement#1]
Installing collected packages: fastapi
  Attempting uninstall: fastapi
    Found existing installation: fastapi 0.63.0
ERROR: Cannot uninstall 'fastapi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by Deepanjalkumar** [comment]
Seems like you already have fastapi (version 0.63.0) installed on your operating system.
Uninstall it and then run the requirements.txt file.

**Comment by dodoaska** [comment]
fastapi version is kali default

**Comment by Deepanjalkumar** [comment]
Well in that case just delete the line where fastapi is mention in
requirements.txt file. Then you are good to go.
